using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Shared.Roslyn;

[Generator]
public class SyncComponentGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var structDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!.Value);

        context.RegisterSourceOutput(structDeclarations, static (spc, source) => Execute(source, spc));
    }

    private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
        => node is StructDeclarationSyntax { AttributeLists.Count: > 0 };

    private static StructSymbolContext? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var structDeclaration = (StructDeclarationSyntax)context.Node;

        foreach (var attributeList in structDeclaration.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                if (context.SemanticModel.GetSymbolInfo(attribute).Symbol is not IMethodSymbol attributeSymbol)
                    continue;

                var attributeContainingTypeSymbol = attributeSymbol.ContainingType;
                var fullName = attributeContainingTypeSymbol.ToDisplayString();

                if (fullName == "Shared.Attributes.SyncComponentAttribute")
                {
                    var symbol = context.SemanticModel.GetDeclaredSymbol(structDeclaration) as INamedTypeSymbol;
                    if (symbol is null) return null;

                    return new StructSymbolContext(symbol);
                }
            }
        }

        return null;
    }

    private static void Execute(StructSymbolContext context, SourceProductionContext spc)
    {
        var symbol = context.Symbol;
        var structName = symbol.Name;
        var namespaceName = symbol.ContainingNamespace.ToDisplayString();
        var syncDataName = $"{structName}_SyncData";

        var fields = symbol.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(f => !f.IsStatic)
            .Where(f => !f.GetAttributes().Any(a => a?.AttributeClass?.ToDisplayString() == "Shared.Attributes.NonSyncedAttribute"))
            .OrderBy(f => f.Name)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using Shared.NetworkUtilities;");
        sb.AppendLine("using MessagePack;");
        sb.AppendLine("using System.Buffers;");
        sb.AppendLine("");
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine("");

        sb.AppendLine("[MessagePackObject]");
        sb.AppendLine($"public struct {syncDataName}");
        sb.AppendLine("{");
        for (var i = 0; i < fields.Count; i++)
        {
            sb.AppendLine($"    [Key({i})]");
            sb.AppendLine($"    public {fields[i].Type.ToDisplayString()} {fields[i].Name.TrimStart('_')};");
        }

        sb.AppendLine("}");
        sb.AppendLine("");

        sb.AppendLine($"partial struct {structName} : ISynced");
        sb.AppendLine("{");
        
        sb.AppendLine($"    public void ApplyField(string fieldName, in {syncDataName} data)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (fieldName)");
        sb.AppendLine("        {");

        foreach (var field in fields)
        {
            var name = field.Name;
            var cleanName = name.TrimStart('_');
            
            sb.AppendLine($"            case \"{name}\":");
            if (name != cleanName) sb.AppendLine($"            case \"{cleanName}\":");
        
            GenerateFieldAssignment(sb, field, "data", "                ");
            sb.AppendLine("                break;");
        }

        sb.AppendLine("            default:");
        sb.AppendLine("                throw new ArgumentException($\"Field {fieldName} not found\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        // Метод сериализации
        sb.AppendLine($"    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine(
            $"    public void Serialize(IBufferWriter<byte> writer, MessagePackSerializerOptions options = null)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var data = new {syncDataName}");
        sb.AppendLine("        {");
        foreach (var field in fields)
        {
            var name = field.Name;
            var cleanName = name.TrimStart('_');
            var val = field.Type.ToDisplayString().Contains("List<") ? $"this.{name}?.ToArray()" : $"this.{name}";
            sb.AppendLine($"            {cleanName} = {val},");
        }

        sb.AppendLine("        };");
        sb.AppendLine("        MessagePackSerializer.Serialize(writer, data, options);");
        sb.AppendLine("    }");

        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    public void Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options = null)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var data = MessagePackSerializer.Deserialize<{syncDataName}>(ref reader, options);");
        
        foreach (var field in fields)
        {
            var name = field.Name;
            var cleanName = name.TrimStart('_');
            var fieldType = field.Type.ToDisplayString();

            if (fieldType.Contains("List<"))
            {
                sb.AppendLine($"        this.{name} = data.{cleanName} != null ? new {fieldType}(data.{cleanName}) : null;");
            }
            else
            {
                sb.AppendLine($"        this.{name} = data.{cleanName};");
            }
        }
        sb.AppendLine("    }");
        
        sb.AppendLine("}");

        spc.AddSource($"{structName}_SyncGenerated.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateFieldAssignment(StringBuilder sb, IFieldSymbol field, string sourceName, string indent = "        ")
    {
        var name = field.Name;
        var cleanName = name.TrimStart('_');
        var fieldType = field.Type.ToDisplayString();

        if (fieldType.Contains("List<"))
        {
            sb.AppendLine($"{indent}this.{name} = {sourceName}.{cleanName} != null ? new {fieldType}({sourceName}.{cleanName}) : null;");
        }
        else
        {
            sb.AppendLine($"{indent}this.{name} = {sourceName}.{cleanName};");
        }
    }

    private readonly struct StructSymbolContext
    {
        public INamedTypeSymbol Symbol { get; }

        public StructSymbolContext(INamedTypeSymbol symbol)
        {
            Symbol = symbol;
        }
    }
}