using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Shared.Roslyn;

[Generator]
public sealed class UnifiedNetworkGenerator : IIncrementalGenerator
{
    private const string SyncAttribute = "Shared.Attributes.SyncComponentAttribute";

    private static readonly string[] TargetAttributeFullNames = [
        "Shared.Attributes.NumeratorAttribute", 
        SyncAttribute,
        "Shared.Attributes.RequestComponentAttribute"
    ];

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var typeDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is TypeDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => GetTypeInfo(ctx))
            .Where(static m => m is not null)
            .Collect();
        
        context.RegisterSourceOutput(typeDeclarations, static (spc, source) => Execute(source, spc));
    }

    private static TypeMetadata? GetTypeInfo(GeneratorSyntaxContext ctx)
    {
        if (ctx.Node is not TypeDeclarationSyntax decl) return null;
        if (ctx.SemanticModel.GetDeclaredSymbol(decl) is not INamedTypeSymbol symbol) return null;

        var hasAttr = symbol.GetAttributes().Any(a => TargetAttributeFullNames.Contains(a.AttributeClass?.ToDisplayString()));
        if (!hasAttr) 
            return null;
        
        var isSynced = symbol.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == SyncAttribute);

        return new TypeMetadata(symbol.ToDisplayString(), isSynced);
    }

    private static void Execute(ImmutableArray<TypeMetadata?> types, SourceProductionContext context)
    {
        var orderedTypes = types
            .Where(t => t != null)
            .Select(t => t!.Value)
            .OrderBy(t => t.FullName)
            .ToImmutableArray();

        if (orderedTypes.IsEmpty) 
            return;
        
        GenerateNumerator(orderedTypes, context);
        GenerateFactory(orderedTypes, context);
    }

    private static void GenerateNumerator(ImmutableArray<TypeMetadata> types, SourceProductionContext context)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("public static class NumeratorGenerator");
        sb.AppendLine("{");
        
        // Метод GetType (ID -> Type)
        sb.AppendLine("    public static Type GetType(int id) => id switch {");
        for (var i = 0; i < types.Length; i++)
            sb.AppendLine($"        {i} => typeof({types[i].FullName}),");
        sb.AppendLine("        _ => throw new ArgumentException() };");

        // Метод GetId (Type -> ID)
        sb.AppendLine("    public static int GetId(Type type) => type switch {");
        for (var i = 0; i < types.Length; i++)
            sb.AppendLine($"        _ when type == typeof({types[i].FullName}) => {i},");
        sb.AppendLine("        _ => throw new ArgumentException() };");

        sb.AppendLine("}");
        context.AddSource("NumeratorGenerator.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateFactory(ImmutableArray<TypeMetadata> types, SourceProductionContext context)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using Shared.NetworkUtilities;");
        sb.AppendLine("using Hypercube.Ecs;");

        sb.AppendLine("public static class NetworkFactory");
        sb.AppendLine("{");

        // Основной метод для сборки сущности из сетевого пакета
        sb.AppendLine("    public static void AddComponentFromPayload(int id, Entity entity, World world, ReadOnlyMemory<byte> data)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (id)");
        sb.AppendLine("        {");
        for (var i = 0; i < types.Length; i++)
        {
            if (!types[i].IsSynced)
                continue;
            
            sb.AppendLine($"            case {i}:");
            sb.AppendLine($"                {{");
            
            sb.AppendLine($"                    var component = new {types[i].FullName}();");
            sb.AppendLine($"                    component.Deserialize(data);");
            sb.AppendLine($"                    world.Add(entity, ref component);");
            
            sb.AppendLine($"                    break;");
            sb.AppendLine($"                }}");
        }
        sb.AppendLine("            default: throw new ArgumentException($\"Unknown component ID: {id}\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        
        sb.AppendLine("    public static void PatchComponentFromPayload(int id, Entity entity, World world, ReadOnlyMemory<byte> data)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (id)");
        sb.AppendLine("        {");
        GenerateCases(sb, types, (type) => $$"""
                                                                 if (world.Has<{{type.FullName}}>(entity))
                                                                 {
                                                                     ref var component = ref world.Get<{{type.FullName}}>(entity);
                                                                     component.Deserialize(data);
                                                                 }
                                             """);
        sb.AppendLine("            default: throw new ArgumentException($\"Unknown component ID: {id}\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine();
        
        sb.AppendLine();
        sb.AppendLine("    public static void RemoveComponent(int id, Entity entity, World world)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (id)");
        sb.AppendLine("        {");
        for (var i = 0; i < types.Length; i++)
        {
            if (!types[i].IsSynced)
                continue;
            
            sb.AppendLine($"            case {i}: world.Remove<{types[i].FullName}>(entity); break;");
        }
        sb.AppendLine("            default: throw new ArgumentException($\"Unknown component ID: {id}\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        context.AddSource("NetworkFactory.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
    
    private static void GenerateCases(StringBuilder sb, ImmutableArray<TypeMetadata> types, Func<TypeMetadata, string> action)
    {
        for (var i = 0; i < types.Length; i++)
        {
            if (!types[i].IsSynced)
                continue;
        
            sb.AppendLine($"            case {i}:");
            sb.AppendLine($"                {{");
            sb.AppendLine(action(types[i]));
            sb.AppendLine($"                    break;");
            sb.AppendLine($"                }}");
        }
    }

    private struct TypeMetadata
    {
        public string FullName { get; }
        public bool IsSynced { get; }
        public TypeMetadata(string fullName, bool isSynced) { FullName = fullName; IsSynced = isSynced; }
    }
}