using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Shared.Roslyn;

[Generator]
public sealed class UnifiedNetworkGenerator : IIncrementalGenerator
{
    private const string SyncAttribute = "Shared.Attributes.SyncComponentAttribute";
    private const string RequestAttribute = "Shared.Attributes.RequestComponentAttribute";

    private static readonly string[] TargetAttributeFullNames = [
        "Shared.Attributes.NumeratorAttribute", 
        SyncAttribute,
        RequestAttribute
    ];

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var typeDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is TypeDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => GetTypeInfo(ctx))
            .Where(static m => m is not null)
            .Collect();
        
        context.RegisterSourceOutput(typeDeclarations, static (spc, source) => Execute(source, spc));
    }

    private static TypeMetadata? GetTypeInfo(GeneratorSyntaxContext ctx)
    {
        if (ctx.Node is not TypeDeclarationSyntax decl) return null;
        if (ctx.SemanticModel.GetDeclaredSymbol(decl) is not INamedTypeSymbol symbol) return null;

        var attrs = symbol.GetAttributes();
        var isSynced = attrs.Any(a => a.AttributeClass?.ToDisplayString() == SyncAttribute);
        var isRequest = attrs.Any(a => a.AttributeClass?.ToDisplayString() == RequestAttribute);
        var hasNumerator = attrs.Any(a => a.AttributeClass?.ToDisplayString() == "Shared.Attributes.NumeratorAttribute");

        if (!isSynced && !isRequest && !hasNumerator) return null;
        
        var fields = isSynced 
            ? symbol.GetMembers()
                .OfType<IFieldSymbol>()
                .Where(f => f.DeclaredAccessibility == Accessibility.Public)
                .Select(f => f.Name)
                .ToImmutableArray()
            : ImmutableArray<string>.Empty;

        return new TypeMetadata(symbol.ToDisplayString(), isSynced, isRequest, fields);
    }

    private static void Execute(ImmutableArray<TypeMetadata?> types, SourceProductionContext context)
    {
        var orderedTypes = types
            .Where(t => t != null)
            .Select(t => t!.Value)
            .OrderBy(t => t.FullName)
            .ToImmutableArray();

        if (orderedTypes.IsEmpty) return;
        
        GenerateNumerator(orderedTypes, context);
        GenerateFactory(orderedTypes, context);
    }

    private static void GenerateNumerator(ImmutableArray<TypeMetadata> types, SourceProductionContext context)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("public static class NumeratorGenerator");
        sb.AppendLine("{");
        sb.AppendLine("    public static Type GetType(int id) => id switch {");
        for (var i = 0; i < types.Length; i++)
            sb.AppendLine($"        {i} => typeof({types[i].FullName}),");
        sb.AppendLine("        _ => throw new ArgumentException() };");

        sb.AppendLine("    public static int GetId(Type type) => type switch {");
        for (var i = 0; i < types.Length; i++)
            sb.AppendLine($"        _ when type == typeof({types[i].FullName}) => {i},");
        sb.AppendLine("        _ => throw new ArgumentException() };");
        sb.AppendLine("}");
        context.AddSource("NumeratorGenerator.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateFactory(ImmutableArray<TypeMetadata> types, SourceProductionContext context)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using MessagePack;");
        sb.AppendLine("using Shared.NetworkUtilities;");
        sb.AppendLine("using Shared.Components;");
        sb.AppendLine("using Shared.Helpers;");
        sb.AppendLine("using Shared.Data;");
        sb.AppendLine("using Hypercube.Ecs.Events;");
        sb.AppendLine("using Hypercube.Ecs;");

        sb.AppendLine("public static class NetworkFactory");
        sb.AppendLine("{");
        
        sb.AppendLine("    public static void AddComponentFromPayload(int id, Entity entity, World world, ref MessagePackReader reader)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (id)");
        sb.AppendLine("        {");
        foreach (var (type, i) in types.Select((t, i) => (t, i)))
        {
            if (!type.IsSynced) continue;
            sb.AppendLine($"            case {i}: {{ var c = new {type.FullName}(); c.Deserialize(ref reader); world.Add(entity, ref c); break; }}");
        }
        sb.AppendLine("            default: throw new ArgumentException();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        
        sb.AppendLine("    public static void PatchComponentFromPayload(int id, Entity entity, World world, long serverTick, ref MessagePackReader reader, IEventBus _eventBus)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (id)");
        sb.AppendLine("        {");
        foreach (var (type, i) in types.Select((t, i) => (t, i)))
        {
            if (!type.IsSynced) continue;
            
            var syncDataName = $"{type.FullName}_SyncData";
            
            sb.AppendLine($"            case {i}:");
            sb.AppendLine("                {");
            sb.AppendLine($"                    if (!world.Has<{type.FullName}>(entity)) break;");
            sb.AppendLine("");
            sb.AppendLine("                    if (world.Has<EntityPredictHistory>(entity) &&");
            sb.AppendLine($"                        world.Get<EntityPredictHistory>(entity).Buffers.TryGetValue({i}, out var fieldBuffers))");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        ref var currentComp = ref world.Get<{type.FullName}>(entity);");
            sb.AppendLine("                        ref var history = ref world.Get<EntityPredictHistory>(entity);");
            sb.AppendLine($"                        var serverData = MessagePackSerializer.Deserialize<{type.FullName}_SyncData>(ref reader);");
            sb.AppendLine("                        bool mispredicted = false;");
            sb.AppendLine("");
            sb.AppendLine("                        for (int f = 0; f < fieldBuffers.Count; f++)");
            sb.AppendLine("                        {");
            sb.AppendLine("                            var buffer = fieldBuffers[f];");
            sb.AppendLine("");
            sb.AppendLine("                            if (FieldHistoryHelper.IsFieldValid(ref buffer, serverTick, ref serverData))");
            sb.AppendLine("                                continue;");
            sb.AppendLine("");
            sb.AppendLine("                            FieldHistoryHelper.WriteField(ref buffer, serverTick, ref serverData);");
            sb.AppendLine("                            currentComp.ApplyField(buffer.FieldName, serverData);");
            sb.AppendLine("                            mispredicted = true;");
            sb.AppendLine("                        }");
            sb.AppendLine("");
            sb.AppendLine("                        if (mispredicted)");
            sb.AppendLine("                        {");
            sb.AppendLine("                            history.NeedsRollback = true;");
            sb.AppendLine("                            history.RollbackTick = history.RollbackTick == 0");
            sb.AppendLine("                                ? serverTick");
            sb.AppendLine("                                : Math.Min(history.RollbackTick, serverTick);");
            sb.AppendLine("                        }");
            sb.AppendLine("                        break;");
            sb.AppendLine("                    }");
            sb.AppendLine("");
            sb.AppendLine($"                    var newComp = new {type.FullName}();");
            sb.AppendLine($"                    var prev = world.Get<{type.FullName}>(entity);");
            sb.AppendLine($"                    ref var curr = ref world.Get<{type.FullName}>(entity);");
            sb.AppendLine($"                    var eventData = new Shared.Events.ComponentDirtyEvent<{type.FullName}>(curr);");
            sb.AppendLine($"                    newComp.Deserialize(ref reader);");
            sb.AppendLine($"                    curr = newComp;");
            sb.AppendLine($"                    _eventBus.Raise(entity, ref curr, ref eventData);");
            sb.AppendLine("                    break;");
            sb.AppendLine("                }");
        }
        sb.AppendLine("            default: throw new ArgumentException();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        
        sb.AppendLine("    public static void WriteComponentHistory(int id, Entity entity, World world, long tick, ref EntityPredictHistory history)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (id)");
        sb.AppendLine("        {");
        foreach (var (type, i) in types.Select((t, i) => (t, i)))
        {
            if (!type.IsSynced || type.Fields.IsEmpty) continue;
            sb.AppendLine($"            case {i}:");
            sb.AppendLine("                {");
            sb.AppendLine($"                    ref var component = ref world.Get<{type.FullName}>(entity);");
            sb.AppendLine($"                    var buffers = history.Buffers[{i}];");
            sb.AppendLine($"                    FieldHistoryBuffer buffer;");
            for (var f = 0; f < type.Fields.Length; f++)
            {
                sb.AppendLine($"                    buffer = buffers[{f}];");
                sb.AppendLine($"                    FieldHistoryHelper.WriteField<{type.FullName}>(ref buffer, tick, ref component);");
            }
            sb.AppendLine("                    break;");
            sb.AppendLine("                }");
        }
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        
        GenerateFooter(sb, types);
        
        sb.AppendLine("    public static object DeserializeRequestComponent(int id, ref MessagePackReader reader)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (id)");
        sb.AppendLine("        {");
        for (int i = 0; i < types.Length; i++) if (types[i].IsRequest) sb.AppendLine($"            case {i}: return {types[i].FullName}.Deserialize(ref reader); break;");
        sb.AppendLine("            default: throw new ArgumentException();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        
        sb.AppendLine("    public static void SerializeRequestComponent(int id, ref MessagePackWriter writer, object request)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (id)");
        sb.AppendLine("        {");
        for (int i = 0; i < types.Length; i++) if (types[i].IsRequest) sb.AppendLine($"            case {i}: {types[i].FullName}.Serialize(ref writer, ({types[i].FullName})request); break;");
        sb.AppendLine("            default: throw new ArgumentException();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        context.AddSource("NetworkFactory.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateFooter(StringBuilder sb, ImmutableArray<TypeMetadata> types)
    {
        sb.AppendLine("    public static void RemoveComponent(int id, Entity entity, World world) { switch(id) {");
        for (var i = 0; i < types.Length; i++) 
            if (types[i].IsSynced) 
                sb.AppendLine($"      case {i}: world.Remove<{types[i].FullName}>(entity); break;");
        sb.AppendLine("    } }");
    }

    private struct TypeMetadata
    {
        public string FullName { get; }
        public bool IsSynced { get; }
        public bool IsRequest { get; }
        public ImmutableArray<string> Fields { get; }
        public TypeMetadata(string fullName, bool isSynced, bool isRequest, ImmutableArray<string> fields) 
        { FullName = fullName; IsSynced = isSynced; IsRequest = isRequest; Fields = fields; }
    }
}